### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by gormleymark** [HearthSim/LotusTracker#99]
Tracker asked me for login today, when I enter it the login button changes to enter but when I click it nothing happens. 
Edit: It seems that it actually does log in, the overlay appears but it's not working, all cards are shown as unknown and no tier lists are showing when drafting.

**Comment by edipo2s** [comment]
Hi, that was because a web server update and the DNS records take a time to update, so the website and API went down some time. Now they are up again, you can try restart Lotus Tracker.

**Comment by gormleymark** [comment]
Confirmed working again, thanks.
